version: '3.6'

services:
  frontend:
    image: khronozz/starwarsarchive-frontend:latest
    container_name: starwarsarchive-frontend
    restart: always
    ports:
      - '8081:4200'
    depends_on:
      - backend

  backend:
    image: khronozz/starwarsarchive-backend:latest
    container_name: starwarsarchive-backend
    restart: always
    ports:
      - '8080:8080'